Modified the Join and Leave Route
Manthan933/Manthan pull request #16
Opened 2021-01-06 19:31 UTC by Rishi-121

![Screenshot (107)](https://user-images.githubusercontent.com/62418363/103811969-c8848d00-5083-11eb-8613-2eb96538ccc3.png)

2021-01-08 06:14 UTC, mohit355 requested changes
Upload all the local files as well that you used for testing.

2021-01-10 10:42 UTC, mohit355 commented
Upload some snapshot of the UI

2021-01-13 04:14 UTC, aavishkarmishra commented on server/controllers/classrooms.js
> +      { $push: { users: user } },
Please define `user` before using it and check that apis are working or not.

2021-01-13 19:51 UTC, vikhyatsingh123 commented on server/routes/classrooms.js
> +const userAuth = require("../middlewares/userAuth");
have you uploaded userAuth.js file?

2021-01-21 12:38 UTC, Rishi-121 commented
No, I am not working on this project.

2021-01-21 12:38 UTC, closed without merging