created code_of_conduct and contributing file
Manthan933/Manthan pull request #22
Opened 2021-01-13 21:49 UTC by Sloth-Panda

corresponds to issue -> #19

2021-01-14 19:12 UTC, mohit355 requested changes

2021-01-14 19:12 UTC, mohit355 commented on CONTRIBUTING.md
> +- Read the Code of Conduct file.
link code of conduct file here

2021-01-14 21:29 UTC, Sloth-Panda commented
@mohit355 has made the pr kindly check and let me  know

2021-01-16 15:31 UTC, harshareddy794 commented
#23 is the latest PR for the issue and #22 can be closed

2021-01-16 15:31 UTC, closed without merging