Updated readme
Manthan933/Manthan pull request #23
Opened 2021-01-13 22:04 UTC by Sloth-Panda

corresponds to issue-> #20

2021-01-14 19:11 UTC, mohit355 requested changes

2021-01-14 19:11 UTC, mohit355 commented on CONTRIBUTING.md
> +- Read the Code of Conduct file.
Link the code of conduct file here

2021-01-16 15:28 UTC, harshareddy794 approved these changes
LGTM! @Sloth-Panda 
Thanks for your contribution to manthan

2021-01-18 08:06 UTC, mohit355 approved these changes

2021-01-18 10:13 UTC, merged

2021-01-18 10:14 UTC, aavishkarmishra commented
Thanks for your contribution @Sloth-Panda 💯